[package]
name = "drudge"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"

[dependencies]
core_affinity = { version = "0.8.1", optional = true }
crossbeam-utils = "0.8.20"
num_cpus = "1.16.0"
parking_lot = "0.12.3"
thiserror = "1.0.63"
# alternate channel implementations that can be enabled with features
crossbeam-channel = { version = "0.5.13", optional = true }
flume = { version = "0.11.1", optional = true }
kanal = { version = "0.1.0-pre8", optional = true }
loole = { version = "0.4.0", optional = true }
paste = "1.0.15"

[dev-dependencies]
serial_test = "3.2.0"
#rstest = "0.22.0"
stacker = "0.1.17"

[features]
default = ["affinity", "retry"] # TODO: remove
affinity = ["dep:core_affinity"]
crossbeam = ["dep:crossbeam-channel"]
flume = ["dep:flume"]
kanal = ["dep:kanal"]
loole = ["dep:loole"]
retry = []
