name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and test all combinations of affinity, retry features
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - run: cargo clippy --all-targets -- -D warnings $(cat .lints | cut -f1 -d"#" | tr '\n' ' ')
      - run: cargo fmt -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-all-features
      - uses: actions-rs/cargo@v1
        with:
          command: build-all-features
          args: --all-targets
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features

  build_and_test_channels:
    name: Build and test with each different channel crate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        channel:
          - default
          - crossbeam
          - flume
          - loole
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-all-features
      - uses: actions-rs/cargo@v1
        with:
          command: build-all-features
          args: -F ${{ matrix.channel }} --all-targets
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -F ${{ matrix.channel }}

  build_and_test_loole:
    name: Build and test all combination of features with loole
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-all-features
      - uses: actions-rs/cargo@v1
        with:
          command: build-all-features
          args: -F loole --all-targets
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: -F loole

  build_and_test_flume:
    name: Build and test all combination of features with flume
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-all-features
      - uses: actions-rs/cargo@v1
        with:
          command: build-all-features
          args: -F flume --all-targets
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: -F flume